name: double_a
description: "Plane Deinen Stundenplan"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.1
  html: ^0.15.4
  animated_custom_dropdown: ^3.1.1
  syncfusion_flutter_calendar: ^27.1.51
  syncfusion_localizations: ^27.1.51
  device_calendar: ^4.3.3

  flex_color_scheme: ^7.3.1
  smooth_page_indicator: ^1.2.0+3
  
  flutter_localizations:
    sdk: flutter
  timezone: ^0.9.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/ca/